default_platform(:android)

platform :android do
  desc "Upload metadata and screenshots to Google Play Store"
  lane :upload_metadata do
    upload_to_play_store(
      json_key: ENV["SUPPLY_JSON_KEY_FILE"],
      track: "internal",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_changelogs: true,
      skip_upload_images: false,
      skip_upload_screenshots: false,
      skip_upload_metadata: false,
      sync_image_upload: true
    )
  end
end
